version: "3.6"

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    command: npm run compose-dev
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks: 
      - dynamodb-development

  dynamodb:
    image: amazon/dynamodb-local
    ports: 
      - '8000:8000'
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data/
    volumes:
      - '${PWD}/local/dynamodb:/data/'
    networks: 
      - dynamodb-development

networks:
  dynamodb-development:
    driver: bridge

volumes: 
  dynamodb-data:
